version: '3.8'  # Update to the latest version
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9000"  # Change port mapping as necessary
    volumes:
      - .:/var/www/html
    networks:
      - laravel

networks:
  laravel:
